language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email: travisci+nx-gameboard@raynode.de
node_js:
  - '10'
script:
  - npm run test
  - npm run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
